name: Complete Football Odds Collection - Fixed

on:
  workflow_dispatch:
    inputs:
      league_filter:
        description: 'Filtrer par ligue (ex: ENG1,FRA1)'
        required: false
        default: ''
        type: string
      batch_size:
        description: 'Taille des batches'
        required: false
        default: '25'
        type: string

jobs:
  collect-complete-odds:
    runs-on: ubuntu-latest
    timeout-minutes: 480
    
    # AJOUT: Permissions explicites pour éviter les problèmes
    permissions:
      contents: write
      actions: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas numpy urllib3

    - name: Create data structure
      run: |
        mkdir -p data/odds/raw_data
        mkdir -p data/odds/summaries
        echo "Structure créée dans data/odds/"

    - name: Check resources
      run: |
        echo "=== RESSOURCES ==="
        df -h
        free -h
        echo "=== FICHIERS EXISTANTS ==="
        ls -la data/ 2>/dev/null || echo "Pas de dossier data"
        ls -la data/odds/raw_data/ 2>/dev/null || echo "Pas de données odds"

    # MODIFICATION: Test API plus robuste
    - name: Test API
      env:
        RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
      run: |
        python3 << 'EOF'
import requests
import os
import sys

print("🔍 Test de l'API...")
headers = {
    'x-rapidapi-host': 'api-football-v1.p.rapidapi.com', 
    'x-rapidapi-key': os.environ.get('RAPIDAPI_KEY', '')
}

if not headers['x-rapidapi-key']:
    print("❌ RAPIDAPI_KEY manquante!")
    sys.exit(1)

print(f"🔑 Clé API: {headers['x-rapidapi-key'][:10]}...")

try:
    response = requests.get(
        'https://api-football-v1.p.rapidapi.com/v3/status', 
        headers=headers, 
        timeout=15
    )
    print(f"📡 Status code: {response.status_code}")
    
    if response.status_code == 200:
        data = response.json()
        print(f"✅ API OK - Plan: {data.get('subscription', {}).get('plan', 'N/A')}")
        print(f"📊 Requêtes restantes: {data.get('subscription', {}).get('requests_remaining', 'N/A')}")
    else:
        print(f"❌ Erreur API: {response.status_code}")
        print(f"📝 Réponse: {response.text[:200]}")
        sys.exit(1)
        
except Exception as e:
    print(f"❌ Erreur: {e}")
    sys.exit(1)
EOF

    - name: Configure parameters
      run: |
        echo "LEAGUE_FILTER=${{ github.event.inputs.league_filter || '' }}" >> $GITHUB_ENV
        echo "BATCH_SIZE=${{ github.event.inputs.batch_size || '25' }}" >> $GITHUB_ENV
        echo "Filtrage: '${{ github.event.inputs.league_filter || 'TOUTES' }}'"
        echo "Batch: ${{ github.event.inputs.batch_size || '25' }}"

    # MODIFICATION: Vérification que le script existe
    - name: Check script exists
      run: |
        if [ ! -f "complete_football_odds_collector.py" ]; then
          echo "❌ Script complete_football_odds_collector.py introuvable!"
          ls -la *.py || echo "Aucun fichier Python trouvé"
          exit 1
        fi
        echo "✅ Script trouvé"

    - name: Prepare script
      run: |
        cp complete_football_odds_collector.py complete_football_odds_collector_filtered.py
        
        if [ ! -z "$LEAGUE_FILTER" ]; then
          echo "🔧 Filtrage par ligues: $LEAGUE_FILTER"
          python3 << 'EOF'
import os

# Lire le fichier
with open('complete_football_odds_collector_filtered.py', 'r', encoding='utf-8') as f:
    content = f.read()

# Obtenir les ligues filtrées
leagues_str = os.environ.get('LEAGUE_FILTER', '').strip()
if leagues_str:
    leagues = [x.strip().upper() for x in leagues_str.split(',') if x.strip()]
    print(f"🎯 Ligues ciblées: {leagues}")
    
    # Modifier le contenu pour filtrer
    filter_code = f"""
        # Filtrage automatique des ligues
        filtered_leagues = {leagues}
        original_leagues = dict(self.all_leagues)
        self.all_leagues = {{k: v for k, v in original_leagues.items() if k in filtered_leagues}}
        logger.info(f"🎯 Filtrage appliqué: {{len(self.all_leagues)}}/{{len(original_leagues)}} ligues")
"""
    
    # Insérer le code de filtrage après l'initialisation
    marker = "# Saisons à analyser"
    if marker in content:
        content = content.replace(marker, filter_code + "\n        " + marker)
        
        with open('complete_football_odds_collector_filtered.py', 'w', encoding='utf-8') as f:
            f.write(content)
        
        print("✅ Script filtré créé")
    else:
        print("⚠️ Marqueur de filtrage non trouvé, script non modifié")
else:
    print("ℹ️ Aucun filtrage appliqué")
EOF
        else
          echo "ℹ️ Aucun filtrage"
        fi

    # MODIFICATION: Exécution avec gestion d'erreurs améliorée
    - name: Run odds collection
      env:
        RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
      run: |
        echo "🚀 DÉBUT COLLECTE: $(date)"
        echo "📝 Configuration:"
        echo "   - Filtrage: ${LEAGUE_FILTER:-'Toutes les ligues'}"
        echo "   - Batch size: ${BATCH_SIZE:-'25'}"
        
        # Exécution avec capture détaillée des erreurs
        set -e  # Arrêter en cas d'erreur
        
        if python3 complete_football_odds_collector_filtered.py 2>&1 | tee collection.log; then
          echo "✅ Script exécuté avec succès"
        else
          exit_code=$?
          echo "❌ Script échoué avec code: $exit_code"
          echo ""
          echo "=== DERNIÈRES LIGNES DU LOG ==="
          tail -50 collection.log || echo "Pas de log disponible"
          echo ""
          echo "=== ERREURS PYTHON ==="
          grep -i "error\|exception\|traceback" collection.log || echo "Pas d'erreur Python détectée"
          exit $exit_code
        fi
        
        echo "🏁 FIN COLLECTE: $(date)"

    # MODIFICATION: Analyse détaillée des résultats
    - name: Analyze results
      run: |
        echo "=== ANALYSE DES RÉSULTATS ==="
        
        # Vérifier la structure
        echo "📁 Structure des dossiers:"
        find data/ -type d | sort || echo "Pas de structure data/"
        
        echo ""
        echo "📊 Fichiers créés:"
        if [ -d "data/odds/raw_data" ]; then
          files=$(find data/odds/raw_data -name "*.csv" | wc -l)
          echo "  📈 Fichiers CSV raw: $files"
          
          if [ $files -gt 0 ]; then
            echo "  📋 Détail des fichiers:"
            for file in data/odds/raw_data/*.csv; do
              if [ -f "$file" ]; then
                lines=$(wc -l < "$file")
                size=$(du -h "$file" | cut -f1)
                echo "    - $(basename "$file"): $((lines-1)) lignes, $size"
              fi
            done
            
            # Compter le total de cotes
            total_odds=0
            for file in data/odds/raw_data/*.csv; do
              if [ -f "$file" ]; then
                count=$(tail -n +2 "$file" | wc -l)
                total_odds=$((total_odds + count))
              fi
            done
            echo "  🎯 Total cotes collectées: $total_odds"
          fi
        else
          echo "  ❌ Dossier raw_data non créé"
        fi
        
        echo ""
        echo "📄 Résumés créés:"
        if [ -d "data/odds/summaries" ]; then
          summary_files=$(find data/odds/summaries -name "*.csv" | wc -l)
          echo "  📊 Fichiers résumés: $summary_files"
        else
          echo "  ❌ Dossier summaries non créé"
        fi
        
        echo ""
        echo "🗃️ Métadonnées:"
        if [ -f "data/odds/collection_metadata.json" ]; then
          echo "  ✅ Métadonnées créées"
        else
          echo "  ❌ Métadonnées manquantes"
        fi

    # MODIFICATION: Commit intelligent amélioré
    - name: Smart commit
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        
        echo "=== PRÉPARATION DU COMMIT ==="
        
        # Vérifier s'il y a des changements
        if [ -z "$(git status --porcelain)" ]; then
          echo "ℹ️ Aucun changement détecté"
          exit 0
        fi
        
        # Analyser les fichiers à committer
        echo "📊 Analyse des fichiers modifiés:"
        git status --porcelain
        
        # Ajouter les fichiers par catégorie
        files_added=0
        
        # 1. Métadonnées et logs (toujours sûrs)
        git add data/odds/collection_metadata.json 2>/dev/null && files_added=$((files_added + 1)) || true
        git add *.log 2>/dev/null && files_added=$((files_added + 1)) || true
        
        # 2. Résumés (généralement petits)
        if [ -d "data/odds/summaries" ]; then
          git add data/odds/summaries/*.csv 2>/dev/null && files_added=$((files_added + 1)) || true
        fi
        
        # 3. Données brutes avec vérification de taille
        large_files=0
        standard_files=0
        total_size=0
        
        if [ -d "data/odds/raw_data" ]; then
          for file in data/odds/raw_data/*.csv; do
            if [ -f "$file" ]; then
              # Obtenir la taille du fichier (compatible Linux/macOS)
              size=$(stat -c%s "$file" 2>/dev/null || stat -f%z "$file" 2>/dev/null)
              total_size=$((total_size + size))
              
              if [ "$size" -gt 75000000 ]; then  # 75MB
                large_files=$((large_files + 1))
                echo "  ⚠️ Fichier volumineux ignoré: $(basename "$file") ($(($size / 1024 / 1024))MB)"
              else
                git add "$file" 2>/dev/null && standard_files=$((standard_files + 1)) || true
                echo "  ✅ Ajouté: $(basename "$file") ($(($size / 1024 / 1024))MB)"
              fi
            fi
          done
        fi
        
        echo ""
        echo "📈 Résumé:"
        echo "  📁 Fichiers standards ajoutés: $standard_files"
        echo "  🚫 Fichiers volumineux ignorés: $large_files"
        echo "  💾 Taille totale: $(($total_size / 1024 / 1024))MB"
        
        # Créer le commit si des fichiers ont été ajoutés
        if ! git diff --staged --quiet; then
          # Créer un message de commit détaillé
          commit_msg="📊 Collecte odds complète - $(date '+%Y-%m-%d %H:%M')

🎯 Configuration:
- Filtrage: ${{ github.event.inputs.league_filter || 'Toutes ligues' }}
- Batch size: ${{ github.event.inputs.batch_size || '25' }}

📈 Résultats:
- Fichiers standards: $standard_files
- Fichiers volumineux: $large_files (non committés)
- Taille données: $(($total_size / 1024 / 1024))MB

🤖 Collecte automatique via GitHub Actions"

          git commit -m "$commit_msg"
          
          # Tenter le push avec retry
          max_attempts=3
          for attempt in $(seq 1 $max_attempts); do
            if git push; then
              echo "✅ Push réussi (tentative $attempt)"
              break
            else
              if [ $attempt -lt $max_attempts ]; then
                echo "⚠️ Push échoué, nouvelle tentative dans 5s..."
                sleep 5
              else
                echo "❌ Push définitivement échoué après $max_attempts tentatives"
                exit 1
              fi
            fi
          done
          
          echo "🎉 Données commitées et poussées avec succès"
        else
          echo "ℹ️ Aucun fichier à committer après filtrage par taille"
        fi

    # MODIFICATION: Upload d'artefacts plus complet
    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: odds-collection-${{ github.run_number }}
        path: |
          data/odds/**/*.csv
          data/odds/**/*.json
          *.log
          complete_football_odds_collector_filtered.py
        retention-days: 30
        if-no-files-found: warn

    - name: Final report
      if: always()
      run: |
        echo "=== RAPPORT FINAL ==="
        echo "🕒 Date: $(date)"
        echo "📊 Status job: ${{ job.status }}"
        echo "🏃 Run ID: ${{ github.run_id }}"
        
        # Statistiques finales
        if [ -d "data/odds" ]; then
          total_size=$(du -sh data/odds 2>/dev/null | cut -f1)
          echo "💾 Taille totale: $total_size"
          
          csv_count=$(find data/odds -name "*.csv" 2>/dev/null | wc -l)
          echo "📈 Fichiers CSV: $csv_count"
          
          if [ -f "data/odds/collection_metadata.json" ]; then
            echo "🗃️ Métadonnées: ✅"
          else
            echo "🗃️ Métadonnées: ❌"
          fi
        else
          echo "❌ Dossier data/odds non créé"
        fi
        
        # Logs d'erreur s'il y en a
        if [ -f "collection.log" ]; then
          error_count=$(grep -c -i "error\|exception\|failed" collection.log || echo "0")
          echo "⚠️ Erreurs détectées: $error_count"
          
          if [ "$error_count" -gt 0 ]; then
            echo ""
            echo "=== DERNIÈRES ERREURS ==="
            grep -i "error\|exception\|failed" collection.log | tail -10 || echo "Aucune erreur trouvée"
          fi
        fi
        
        echo ""
        echo "🎯 Artefacts: odds-collection-${{ github.run_number }}"
        echo "⏰ Rétention: 30 jours"
        echo ""
        
        if [ "${{ job.status }}" = "success" ]; then
          echo "🎉 COLLECTE TERMINÉE AVEC SUCCÈS!"
        else
          echo "❌ COLLECTE ÉCHOUÉE - Consultez les logs et artefacts"
        fi
