# .github/workflows/football_data_collection.yml
name: Football Big 5 Data Collection

# Déclenchement tous les lundis à 6h00 UTC
on:
  schedule:
    - cron: '0 6 * * 1'  # Tous les lundis à 6h00 UTC
  workflow_dispatch:  # Permet de lancer manuellement le workflow

jobs:
  collect-data:
    runs-on: ubuntu-latest
    
    steps:
    # Étape 1: Checkout du code
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    # Étape 2: Configuration de Python
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    # Étape 3: Installation des dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas
    
    # Étape 4: Création du dossier data
    - name: Create data directory
      run: mkdir -p data
    
    # Étape 5: Exécution du script de collecte
    - name: Run football data collection
      env:
        RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
      run: |
        # Modification du script pour utiliser la variable d'environnement
        python -c "
        import os
        import sys
        
        # Import du script principal
        exec(open('football_data_collector.py').read().replace(
            'RAPIDAPI_KEY = \"YOUR_RAPIDAPI_KEY\"',
            'RAPIDAPI_KEY = os.environ.get(\"RAPIDAPI_KEY\")'
        ))
        "
    
    # Étape 6: Commit et push des nouveaux fichiers CSV
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/*.csv
        git add football_data.log
        
        # Vérifier s'il y a des changements à committer
        if git diff --staged --quiet; then
          echo "Aucun changement à committer"
        else
          git commit -m "🔄 Mise à jour automatique des données Big 5 - $(date '+%Y-%m-%d')"
          git push
        fi
    
    # Étape 7: Upload des logs en cas d'erreur
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: football-data-logs
        path: football_data.log
    
    # Étape 8: Résumé des fichiers générés
    - name: Display summary
      run: |
        echo "=== RÉSUMÉ DE LA COLLECTE ==="
        echo "Date: $(date)"
        echo "Fichiers générés:"
        ls -la data/
        echo ""
        echo "Taille des fichiers:"
        du -h data/*.csv 2>/dev/null || echo "Aucun fichier CSV trouvé"
        echo ""
        echo "Dernières lignes du log:"
        tail -10 football_data.log 2>/dev/null || echo "Aucun log trouvé"
