# .github/workflows/football_data_collection.yml
name: Football Data Collection (All Leagues)

on:
  workflow_dispatch:  # Permet de lancer manuellement le workflow

jobs:
  collect-data:
    runs-on: ubuntu-latest
    
    steps:
    # Étape 1: Checkout du code
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    # Étape 2: Configuration de Python
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    # Étape 3: Installation des dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas
    
    # Étape 4: Création de la structure de dossiers
    - name: Create data directory
      run: mkdir -p data/matches
    
    # Étape 5: Exécution du script de collecte étendu
    - name: Run extended football data collection
      env:
        RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
      run: |
        python src/data_processing/football_data_collector_extended.py
    
    # Étape 6: Commit et push des nouveaux fichiers CSV
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/matches/*.csv
        git add logs/football_data_extended.log
        
        # Vérifier s'il y a des changements à committer
        if git diff --staged --quiet; then
          echo "Aucun changement à committer"
        else
          git commit -m "📊 Mise à jour des données de match (15 ligues) - $(date '+%Y-%m-%d')"
          git push
        fi
    
    # Étape 7: Upload des logs en cas d'erreur
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: football-data-logs
        path: logs/football_data_extended.log
    
    # Étape 8: Résumé des fichiers générés
    - name: Display summary
      run: |
        echo "=== RÉSUMÉ DE LA COLLECTE ==="
        echo "Date: $(date)"
        echo "Fichiers générés dans data/matches/:"
        ls -la data/matches/
        echo ""
        echo "Taille des fichiers:"
        du -h data/matches/*.csv 2>/dev/null || echo "Aucun fichier CSV trouvé"
        echo ""
        echo "Dernières lignes du log:"
        tail -10 logs/football_data_extended.log 2>/dev/null || echo "Aucun log trouvé"
