# .github/workflows/main_pipeline.yml
name: Main Football Prediction Pipeline

on:
  schedule:
    - cron: '0 8 * * *'  # Tous les jours à 8h00 UTC (après la mise à jour des données)
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

  run-elo-calculator:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Elo Calculator
        run: python src/analysis/elo_calculator.py

      - name: Upload data artifacts
        uses: actions/upload-artifact@v4
        with:
          name: data-after-elo
          path: data/

  update-results:
    needs: run-elo-calculator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download data artifacts
        uses: actions/download-artifact@v4
        with:
          name: data-after-elo
          path: data/

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Results Updater
        run: python src/data_processing/results_updater.py

      - name: Upload data with results
        uses: actions/upload-artifact@v4
        with:
          name: data-with-results
          path: data/

  run-elo-summary:
    needs: update-results
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download data artifacts
        uses: actions/download-artifact@v4
        with:
          name: data-with-results
          path: data/

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Elo Summary
        run: python src/analysis/elo_summary.py

      - name: Upload data artifacts
        uses: actions/upload-artifact@v4
        with:
          name: data-after-summary
          path: data/

  run-prediction-workflows:
    needs: run-elo-summary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download data artifacts
        uses: actions/download-artifact@v4
        with:
          name: data-after-summary
          path: data/

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Elo Prediction Workflow
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: python -m src.prediction.elo_prediction_workflow

      - name: Run Daily Prediction Workflow
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: python -m src.prediction.daily_predictions_workflow

      - name: Commit and push predictions
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/predictions/*.csv
          if git diff --staged --quiet; then
            echo "Aucun changement dans les prédictions."
          else
            git commit -m "🔮 Mise à jour des prédictions quotidiennes - $(date '+%Y-%m-%d')"
            git push
          fi

      - name: Upload final data for site generation
        uses: actions/upload-artifact@v4
        with:
          name: final-data
          path: data/

  build-site:
    needs: run-prediction-workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download final data
        uses: actions/download-artifact@v4
        with:
          name: final-data
          path: data/

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate static site
        run: python src/site_generator/generator.py

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/

  deploy-site:
    needs: build-site
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
